# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hurra_agent.proto for package 'proto'

require 'grpc'
require 'hurra_agent_pb'

module Proto
  module HurraAgent
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.HurraAgent'

      rpc :MountDrive, Proto::MountDriveRequest, Proto::MountDriveResponse
      rpc :UnmountDrive, Proto::UnmountDriveRequest, Proto::UnmountDriveResponse
      rpc :GetDrives, Proto::GetDrivesRequest, Proto::GetDrivesResponse
      rpc :LoadImage, Proto::LoadImageRequest, Proto::LoadImageResponse
      rpc :UnloadImage, Proto::UnloadImageRequest, Proto::UnloadImageResponse
      rpc :RunContainer, Proto::RunContainerRequest, Proto::RunContainerResponse
      rpc :KillContainer, Proto::KillContainerRequest, Proto::KillContainerResponse
      rpc :RunContainerSpec, Proto::ContainerSpecRequest, Proto::ContainerSpecResponse
      rpc :StopContainerSpec, Proto::ContainerSpecRequest, Proto::ContainerSpecResponse
      rpc :StartContainerInSpec, Proto::ContainerSpecRequest, Proto::ContainerSpecResponse
      rpc :StopContainerInSpec, Proto::ContainerSpecRequest, Proto::ContainerSpecResponse
      rpc :RemoveContainerSpec, Proto::ContainerSpecRequest, Proto::ContainerSpecResponse
      rpc :ExecInContainerSpec, Proto::ExecInContainerSpecRequest, Proto::ExecInContainerSpecResponse
      rpc :ExecCommand, Proto::Command, Proto::Result
    end

    Stub = Service.rpc_stub_class
  end
end
