# cloud-build.yaml
steps:
  # decrypt gcloud json secret
  - name: gcr.io/cloud-builders/gcloud
    args:
    - kms
    - decrypt
    - --ciphertext-file=cloudbuild/creds.json.enc
    - --plaintext-file=$_CONTEXT/creds.json
    - --location=global
    - --keyring=cloudbuild
    - --key=cloudbuild
  
  # run docker daemon
  - name: 'docker/compose:1.24.1'
    args: ['-f', 'cloudbuild/docker-compose.yml', 'up', '-d', 'docker']
  
  # build image
  - name: 'docker/compose:1.24.1'
    args: ['-f', 'cloudbuild/docker-compose.yml', 'up', 'docker-build']
    env:
    - 'IMAGE=gcr.io/$PROJECT_ID/$_APP_NAME'
    - 'DOCKER_FILE=$_DOCKER_FILE'
    - 'CONTEXT=$_CONTEXT'
  
timeout: 7200s
