# cloud-build.yaml
steps:
  # decrypt gcloud json secret
  - name: gcr.io/cloud-builders/gcloud
    args:
    - kms
    - decrypt
    - --ciphertext-file=cloudbuild/creds.json.enc
    - --plaintext-file=creds.json
    - --location=global
    - --keyring=cloudbuild
    - --key=cloudbuild
  
  # run docker daemon
  - name: 'docker/compose:1.24.1'
    args: ['-f', 'cloudbuild/docker-compose.yml', 'up', '-d', 'docker']
  
  # build image
  - name: 'docker/compose:1.24.1'
    args: ['-f', 'cloudbuild/docker-compose.yml', 'up', 'docker-build']
    env:
    - 'IMAGE=gcr.io/$PROJECT_ID/nginx-proxy:$COMMIT_SHA'
    - 'DOCKER_FILE=Dockerfile'
    - 'CONTEXT=nginx-proxy'
  
timeout: 7200s
