version: '3.7'
services:
  docker:
    image: "docker:dind"
    command: ["--experimental"]
    privileged: true
    volumes:
      - docker-certs-client:/certs/client
      - docker-certs-ca:/certs/ca
    expose:
      - 2376
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      - docker-in-docker-network

  docker-build:
    image: gcr.io/hurrabuild/docker-buildx
    working_dir: /project
    entrypoint: /bin/sh -c
    command: 
      - |
        while [ ! -f  /certs/client/ca.pem  ]; do sleep 2; done
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker context create build
        docker buildx create --use --name build build
        cat creds.json | docker login -u _json_key --password-stdin https://gcr.io
        if [ !-z '$BASE_STAGE' ]; then
          docker buildx build . \
              --target '$BASE_STAGE' \
              --platform linux/amd64,linux/arm64 \
              --f '$DOCKER_FILE' \
              --t '$CACHE_IMAGE:$BASE_STAGE' \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --cache-from '$IMAGE:$BASE_STAGE' 
          $BASE_CACHE="--cache-from=$IMAGE:$BASE_STAGE --build-arg BASE_IMAGE=$IMAGE:$BASE_STAGE"
        fi

        docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            -f '$DOCKER_FILE' \
            -t '$IMAGE' \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --cache-from '$IMAGE' $BASE_CACHE \
            --push
    privileged: true
    depends_on: 
      - docker
    volumes:
      - docker-certs-client:/certs/client:ro
      - ../${CONTEXT:-}:/project
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_BUILDKIT=1
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - DOCKER_TLS_VERIFY=1
      - BUILDKIT_INLINE_CACHE=1
    networks:
      - docker-in-docker-network

volumes:
  docker-certs-ca:
  docker-certs-client:
networks:
  docker-in-docker-network:
