#!/bin/bash
set -e
sudo date
gcloud compute scp hurra-build:/mnt/hurracloud/hurracloud/yocto/build-rpi3/tmp/deploy/images/raspberrypi4-64/core-image-base-raspberrypi4-64.sdimg ./ --project hurrabuild --zone us-east1-b

# sudo dd if=./core-image-base-raspberrypi4-64.sdimg of=/dev/sda
sudo bmaptool copy ./core-image-base-raspberrypi4-64.sdimg /dev/sda
