# -*- mode: ruby -*-
# vi: set ft=ruby :
# Modified version of https://github.com/keithel/yocto-vagrant

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "../", "/home/vagrant/app", type: "nfs"
  config.disksize.size = '100GB'
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 8192
      vb.cpus = 4    
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.host_vars = {
            "default" => {
                "ansible_python_interpreter" => "auto_legacy_silent"
            }
        }
  end
end
