version: '2.4'
services:
  samaa:
    image: gcr.io/hurrabuild/samaa:latest
    build:
      context: ./src/samaa
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - hurracloud

networks:
  hurracloud:
    ipam:
      config:
        - subnet: 172.18.0.0/16

