version: '2.3'
services:
  app-runner:
    image: aimannajjar/hurracloud:app-runner-v1
    build:
      context: .
      dockerfile: AppRunner.Dockerfile
      args:
        - BUILD_DEV=1
    user: root
    volumes:
      - ./app-store/openvpn/ui:/usr/src/app-runner/client/src/HurraApp
      - ./app-store/openvpn/backend:/usr/src/app-runner/server/src/HurraApp
    ports:
      - 3001:3000
    networks:
      - app-network
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm startRunner"    

networks:
  app-network: {}
