version: '2.4'
services:
  elasticsearch:
    ports:
      - 9200:9200
  
  jawhar:
    volumes:
      - ./jawhar:/app
    command: sh -c "bundle install --with development && ./bin/start_jawhar.sh"
    environment:
    - RAILS_ENV=development

  samaa:
    image: node:14.8.0-alpine
    working_dir: /home/node
    volumes:
      - ./samaa:/home/node/
    command: npm run-script start
    stdin_open: true
    networks:
      - hurracloud
    environment:
      - NODE_ENV=development
      - PORT=80