version: '2.3'
services:
  elasticsearch:
    ports:
      - 9200:9200
    
  zahif:
    volumes:
      - ./jawhar:/usr/share/hurracloud/jawhar
    command: sh -c "bundle install && ./bin/start_zahif.sh"

  jawhar:
    build:
      context: .
      dockerfile: Jawhar.Dockerfile
    volumes:
      - ./jawhar:/usr/share/hurracloud/jawhar
    ports:
      - 5000:3000
    command: sh -c "bundle install && ./bin/start_jawhar.sh"

  samaa:
    image: aimannajjar/hurracloud:samaa-v1
    build:
      context: .
      dockerfile: Samaa.Dockerfile
      args:
        - BUILD_DEV=1
    user: root
    volumes:
      - ./samaa:/usr/src/samaa
    command: sh -c "yarn install && yarn start"    
    ports:
      - 3000:3000
    networks:
      - hurracloud
    environment:
      - NODE_ENV=development
