version: '2.4'
services:
  samaa:
    image: node:14.8.0-alpine
    working_dir: /home/node
    volumes:
      - ./samaa:/home/node/
    command: npm run-script start
    stdin_open: true
    networks:
      - hurracloud
    environment:
      - NODE_ENV=development
      - PORT=80