version: '2.4'
services:
  # elasticsearch:
  #   ports:
  #     - 9200:9200

  # jawhar:
  #   volumes:
  #     - ./jawhar:/app
  #   command: >
  #     sh -c "bundle install --with development &&
  #            rm -rf /app/tmp/pids/server.pid &&
  #            BACKGROUND=yes QUEUE=* rake resque:work &&
  #            rails s -b '0.0.0.0' -p 5000"
  #   environment:
  #   - RAILS_ENV=development
  #   stdin_open: true
  #   ports:
  #   - 5000:5000

  samaa:
    image: node:14.8.0-alpine
    working_dir: /home/node
    volumes:
      - ./samaa:/home/node/
    command: npm run-script start
    stdin_open: true
    networks:
      - hurracloud
    environment:
      - NODE_ENV=development
      - PORT=80