version: '2.3'
services:
  zahif:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes_from:
    - jawhar
    command: ./bin/start_zahif.sh
    environment:
    - RAILS_ENV=indexer
    networks:
      - hurracloud
    restart: always

  jawhar:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes:
      - ./data/indices:/usr/share/hurracloud/zahif/indices
      - ./data/db:/usr/share/hurracloud/jawhar/data
      - ./data/logs:/usr/share/hurracloud/jawhar/log
      - ./key:/root/.ssh/id_rsa
      - /dev/bus/usb:/dev/bus/usb
      - type: bind
        source: ./mounts
        target: /usr/share/hurracloud/mounts
        bind:
          propagation: shared
    environment:
    - HOST_MOUNT_PATH=/usr/share/hurracloud/mounts/
    networks:
      - hurracloud
    privileged: true
    restart: always

  samaa:
    image: aimannajjar/hurracloud:samaa-v1
    networks:
      - hurracloud
    environment:
      - NODE_ENV=production
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=hurracloud
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - hurracloud
    restart: always

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - hurracloud

  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - hurracloud
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./mounts
        target: /mount
        bind:
          propagation: shared
    command: '-u "aiman;Ytz8fJaaxqhdQkpAMnGLOyOkix1" -s "drives;/mount;yes;no;no;aiman;aiman,aiman" -w "HURRA"'

  ftp:
    image: vimagick/pure-ftpd
    ports:
      - "21:21"
    volumes:
      - type: bind
        source: ./mounts
        target: /home/ftpuser
        bind:
          propagation: shared

    privileged: true
    restart: always

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  hurracloud:
    ipam:
      config:
        - subnet: 172.18.0.0/16

