version: '2.4'
services:
  samaa:
    image: gcr.io/hurrabuild/samaa:latest
    build:
      context: .
      dockerfile: Samaa.Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hurracloud

  sonic:
    image: valeriansaliou/sonic:v1.3.0
    restart: unless-stopped
    ports:
      - 1491:1491
    volumes:
      - sonic:/var/lib/sonic/store/
      - ./sonic.cfg:/etc/sonic.cfg
    networks:
      - hurracloud

volumes:
  sonic:

networks:
  hurracloud:
    ipam:
      config:
        - subnet: 172.18.0.0/16

