version: '2.2'
services:
  zahif:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes:
      - ./zahif/indices:/usr/share/hurracloud/zahif/indices
      - ./zahif/logs:/usr/share/hurracloud/zahif/logs
      - ./jawhar/db:/usr/share/hurracloud/jawhar/db      
      - /mnt:/usr/share/hurracloud/jawhar/sources      
    command: bundle exec sidekiq
    networks:
      - hurracloud

  jawhar:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes:
      - ./zahif/indices:/usr/share/hurracloud/zahif/indices
      - ./jawhar/db:/usr/share/hurracloud/jawhar/db
      - /mnt:/usr/share/hurracloud/jawhar/sources
    networks:
      - hurracloud

  samaa:
    image: aimannajjar/hurracloud:samaa-v1
    networks:
      - hurracloud
    environment:
      - NODE_ENV=production

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=hurracloud
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - hurracloud
    # PUT _template/all
    # {
    #   "index_patterns": ["*"],
    #   "settings": {
    #     "number_of_shards": 1,
    #     "number_of_replicas": 1
    #   }
    # }

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - hurracloud

volumes:
  esdata1:
    driver: local
  redis-data:
    driver: local

networks:
  hurracloud:
