version: '2.3'
services:
  zahif:
    image: registry.local:10001/hurracloud:jawhar-v1
    volumes_from:
    - jawhar
    command: ./bin/start_zahif.sh
    environment:
    - RAILS_ENV=indexer
    networks:
      - hurracloud
    restart: always
    privileged: true

  jawhar:
    image: registry.local:10001/hurracloud:jawhar-v1
    volumes:
      - ./data/indices:/usr/share/hurracloud/zahif/indices
      - ./data/db:/usr/share/hurracloud/jawhar/data
      - ./data/logs:/usr/share/hurracloud/jawhar/log
      - ./data/gdfuse:/usr/share/hurracloud/jawhar/gdfuse
      - ./data/apps:/usr/share/hurracloud/jawhar/apps
      - ./appStore:/usr/share/hurracloud/jawhar/appStore-temp ## must be replaced by store.hurrranet.net
      - ./key:/root/.ssh/id_rsa
      - /dev/bus/usb:/dev/bus/usb
      - type: bind
        source: ${MOUNTS_DIR:?err}
        target: /usr/share/hurracloud/mounts
        bind:
          propagation: shared
    environment:
    - HOST_GDFUSE_PATH=/usr/share/hurracloud/data/gdfuse
    - HOST_APPS_PATH=/usr/share/hurracloud/data/apps
    - HOST_MOUNTS_PATH=${MOUNTS_DIR:?err}
    - SKIP_PARTITIONS="" # comma-separated list
    - SAMAA_ROOT_URL=http://localhost:3000
    networks:
      - hurracloud
    privileged: true
    restart: "always"

  samaa:
    image: registry.local:10001/hurracloud:samaa-v1
    networks:
      - hurracloud
    volumes:
      - ./apps:/usr/src/samaa/src/apps
    environment:
      - NODE_ENV=production
      - REACT_APP_JAWHAR_API=http://localhost:5000
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=hurracloud
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "http.cors.allow-origin=*"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - hurracloud
    restart: always

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - hurracloud

  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - hurracloud
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ${MOUNTS_DIR:?err}
        target: /mount
        bind:
          propagation: shared
    command: '-u "aiman;Ytz8fJaaxqhdQkpAMnGLOyOkix1" -s "drives;/mount;yes;no;no;aiman;aiman,aiman" -w "HURRA"'

  webdav:
    image: registry.local:10001/webdav:latest    
    build:
      context: .
      dockerfile: WebDAV.Dockerfile      
    restart: always
    ports:
      - "80:80"
    environment:
      AUTH_TYPE: Digest
      USERNAME: aiman
      PASSWORD: Ytz8fJaaxqhdQkpAMnGLOyOkix1
    volumes:
      - type: bind
        source: ${MOUNTS_DIR:?err}
        target: /var/lib/dav/data
        bind:
          propagation: shared

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  hurracloud:
    ipam:
      config:
        - subnet: 172.18.0.0/16

