version: '2.4'
services:
  zahif:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes_from:
    - jawhar
    command: ./bin/start_zahif.sh
    environment:
    - RAILS_RESQUE_ENV=indexer
    - RAILS_ENV=production
    - SECRET_KEY_BASE=40dec136b707f2a4f7913637c3c5f4dde158a814765969a2bf800911d2227a93ea3697d511075a008131239c1296dae1eb4ed54d19ecf2c4162f7f04265bf539
    networks:
      - hurracloud
    restart: always
    privileged: true

  jawhar:
    image: aimannajjar/hurracloud:jawhar-v1
    volumes:
      - ./data/indices:/usr/share/hurracloud/zahif/indices
      - ./data/db:/usr/share/hurracloud/jawhar/data
      - ./data/logs:/usr/share/hurracloud/jawhar/log
      - ./data/gdfuse:/usr/share/hurracloud/jawhar/gdfuse
      - ./data/apps:/usr/share/hurracloud/jawhar/apps
      - ./appStore:/usr/share/hurracloud/jawhar/appStore-temp
      - ./key:/root/.ssh/id_rsa
      - /dev/bus/usb:/dev/bus/usb
      - type: bind
        source: ${PWD}/mounts
        target: /usr/share/hurracloud/mounts
        bind:
          propagation: shared
    environment:
    - HOST_GDFUSE_PATH=${PWD}/data/gdfuse
    - HOST_APPS_PATH=${PWD}/data/apps
    - HOST_MOUNTS_PATH=${PWD}/mounts
    - SKIP_PARTITIONS="" # comma-separated list
    - SAMAA_ROOT_URL=http://${HURRA_HOSTNAME:-localhost}:3000
    - HURRA_HOSTNAME=${HURRA_HOSTNAME:-localhost}
    - HOST_APP_STORE_PATH=${PWD}/appStore
    - RAILS_ENV=production
    - SECRET_KEY_BASE=40dec136b707f2a4f7913637c3c5f4dde158a814765969a2bf800911d2227a93ea3697d511075a008131239c1296dae1eb4ed54d19ecf2c4162f7f04265bf539
    networks:
      - hurracloud
    privileged: true
    restart: "always"
    ports:
      - 5000:3000

  samaa:
    image: aimannajjar/hurracloud:samaa-v1
    networks:
      - hurracloud
    volumes:
      - ./apps:/usr/src/samaa/src/apps
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - 3000:3000

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1-${ARCH}
    container_name: elasticsearch
    environment:
      - cluster.name=hurracloud
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "http.cors.allow-origin=*"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - hurracloud
    restart: always

  redis:
    image: redis:5.0.3-alpine
    ports:
      - 6379
    volumes:
      - redis-data:/data
    networks:
      - hurracloud
    restart: "always"

volumes:
  es-data:
    driver: local
  redis-data:
    driver: local

networks:
  hurracloud:
    ipam:
      config:
        - subnet: 172.18.0.0/16

