version: '2.4'
services:
  samaa:
    image: gcr.io/hurrabuild/samaa:latest
    build:
      context: ./src/samaa
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WDS_SOCKET_PORT: 0
