version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - cluster.name=hurracloud
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - hurracloud

  indexer:
    image: aimannajjar/hurracloud:indexer-v1
    volumes:
      - /usr/share/hurracloud/indexer/indices:/usr/share/hurracloud/indexer/indices
      - /usr/share/hurracloud/indexer/logs:/usr/share/hurracloud/indexer/logs
      - /mnt:/usr/share/hurracloud/indexer/sources      
    networks:
      - hurracloud

volumes:
  esdata1:
    driver: local

networks:
  hurracloud:
