version: '2.4'
services:
  samaa:
    image: node:14.8.0
    working_dir: /home/node
    volumes:
      - ./src/samaa:/home/node/
    command: npm run-script start
    stdin_open: true
    environment:
      - NODE_ENV=development
      - PORT=80
    extra_hosts:
      - "host.docker.internal:host-gateway"

