// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hurra_agent.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Result struct {
	ExitCode             int32    `protobuf:"varint,1,opt,name=exitCode,proto3" json:"exitCode,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{0}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

func (m *Result) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Command struct {
	Command              string   `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1a676bd7648f983, []int{1}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*Result)(nil), "proto.Result")
	proto.RegisterType((*Command)(nil), "proto.Command")
}

func init() {
	proto.RegisterFile("hurra_agent.proto", fileDescriptor_d1a676bd7648f983)
}

var fileDescriptor_d1a676bd7648f983 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x28, 0x2d, 0x2a,
	0x4a, 0x8c, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x76, 0x5c, 0x6c, 0x41, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x52, 0x5c, 0x1c, 0xa9,
	0x15, 0x99, 0x25, 0xce, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x70, 0xbe,
	0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x31, 0x50, 0xbf, 0x04, 0x13, 0x50, 0x8a, 0x33, 0x08,
	0xc6, 0x55, 0x52, 0xe6, 0x62, 0x77, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x01, 0x29, 0x4a, 0x86,
	0x30, 0x25, 0x98, 0x21, 0x8a, 0xa0, 0x5c, 0x23, 0x1b, 0x2e, 0x2e, 0x0f, 0x90, 0x03, 0x1c, 0x41,
	0xf6, 0x0b, 0xe9, 0x71, 0x71, 0xbb, 0x56, 0xa4, 0x26, 0xc3, 0xb4, 0xf1, 0x41, 0x1c, 0xa4, 0x07,
	0xe5, 0x4b, 0xf1, 0x42, 0xf9, 0x10, 0x67, 0x29, 0x31, 0x38, 0x99, 0x73, 0x49, 0x67, 0xe6, 0xeb,
	0xa5, 0x17, 0x15, 0x24, 0xeb, 0xa5, 0x56, 0x24, 0xe6, 0x16, 0xe4, 0xa4, 0x16, 0xeb, 0x15, 0xe5,
	0x97, 0x96, 0xa4, 0xa6, 0x97, 0x66, 0xa6, 0xa4, 0x3a, 0xf1, 0x07, 0x81, 0xd8, 0xee, 0x20, 0x76,
	0x00, 0x48, 0x63, 0x00, 0x63, 0x14, 0xc4, 0x6f, 0x49, 0x6c, 0x60, 0xca, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xac, 0x96, 0xc8, 0x15, 0xfe, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// HurraAgentClient is the client API for HurraAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HurraAgentClient interface {
	ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error)
}

type hurraAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHurraAgentClient(cc grpc.ClientConnInterface) HurraAgentClient {
	return &hurraAgentClient{cc}
}

func (c *hurraAgentClient) ExecCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/proto.HurraAgent/ExecCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HurraAgentServer is the server API for HurraAgent service.
type HurraAgentServer interface {
	ExecCommand(context.Context, *Command) (*Result, error)
}

// UnimplementedHurraAgentServer can be embedded to have forward compatible implementations.
type UnimplementedHurraAgentServer struct {
}

func (*UnimplementedHurraAgentServer) ExecCommand(ctx context.Context, req *Command) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}

func RegisterHurraAgentServer(s *grpc.Server, srv HurraAgentServer) {
	s.RegisterService(&_HurraAgent_serviceDesc, srv)
}

func _HurraAgent_ExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HurraAgentServer).ExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HurraAgent/ExecCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HurraAgentServer).ExecCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

var _HurraAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HurraAgent",
	HandlerType: (*HurraAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecCommand",
			Handler:    _HurraAgent_ExecCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hurra_agent.proto",
}
