---
version: '2.3'
services:
  server:
    cap_add:
     - NET_ADMIN
    network_mode: "host"
    image: aimannajjar/hurracloud:openvpn-aarch64
    ports:
     - "1194:1194/udp"
    restart: always
    privileged: true
    volumes:
     - openvpn-data:/etc/openvpn

  pki:
    image: aimannajjar/hurracloud:openvpn-aarch64
    network_mode: "host"
    restart: unless-stopped
    command: "/bin/bash -c 'trap : TERM INT; (while sleep 3600; do :; done) & wait'"
    volumes:
     - openvpn-data:/etc/openvpn
     - ./CONTENT/scripts/easyrsa.sh:/usr/local/bin/easyrsa
     - ./CONTENT/scripts/ovpn_initpki.sh:/usr/local/bin/ovpn_initpki
     - ./CONTENT/scripts/gen_client_ovpn.sh:/usr/local/bin/gen_client_ovpn
     - ./CONTENT/scripts/setup_vpn_server.sh:/usr/local/bin/setup_vpn_server
     - ./CONTENT/scripts/create_new_user.sh:/usr/local/bin/create_new_user
     - ./CONTENT/scripts/revoke_user.sh:/usr/local/bin/revoke_user

volumes:
  openvpn-data:
    driver: local

