---
version: '2'
services:
  openvpn_server:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - openvpn-data:/etc/openvpn

  openvpn_pki:
    image: kylemanna/openvpn
    restart: unless-stopped
    command: "/bin/bash -c 'trap : TERM INT; (while sleep 3600; do :; done) & wait'"
    volumes:
     - openvpn-data:/etc/openvpn

volumes:
  openvpn-data:
    driver: local
