inline_files: # files that can be returned as "inline" content-disposition for view action
  allowed_mimes:
    - application/pdf
    - image/jpeg
    - image/gif
    - image/png
    - image/svg+xml
    - image/tiff
    - image/bmp
    - image/webp
    - image/x-icon
    - text/css
    - text/csv
    - text/plain    
mounts_path: /data/mounts
gdfuse_path: /data/gdfuse
fscrawler_root_path: /data/indices 
apps_path: /data/apps
supported_fs_types:
 - iso9660
 - vfat
 - ntfs
 - fat32
 - ext4
