#!/bin/sh
export MACHINE_TYPE=`uname -m`
if [ ${MACHINE_TYPE} == 'x86_64'  ]; then
    ARCH="amd64"
else
    ARCH="arm64"
fi

HOSTNAME=$(sh -c 'hostname -a || hostname' 2>/dev/null)

ROOT="" HURRA_HOSTNAME=$HOSTNAME ARCH=$ARCH docker-compose -f /services.yml stop
