#!/bin/sh
# Requirements
# 1. https://github.com/astrada/google-drive-ocamlfuse (see https://github.com/astrada/google-drive-ocamlfuse/issues/571#issuecomment-533380311)
# 2. ntfs-3d
# 3. hurra-agent
mkdir -p /data/mounts/internal-1
mkdir -p /data/es && chown 1000:1000 /data/es

export MACHINE_TYPE=`uname -m`
if [ ${MACHINE_TYPE} == 'x86_64'  ]; then
    ARCH="amd64"
else
    ARCH="arm64"
fi

IP_ADDRESSES=$(ifconfig | awk -F "[: ]+" '/inet addr:/ { if ($4 != "127.0.0.1" && $4 != "172.17.0.1" && $4 != "172.18.0.1") print $4 }' | xargs echo)
for IP in $IP_ADDRESSES; do
  HOSTNAME=$(avahi-resolve -a $IP | cut -f 2)
  if [ "$HOSTNAME" != "" ]; then
     break;
  fi
done;

if [ "$HOSTNAME" == "" ]; then
   HOSTNAME=$(sh -c 'hostname -a || hostname' 2>/dev/null)
fi
 
ROOT="" HURRA_HOSTNAME=$HOSTNAME ARCH=$ARCH docker-compose -f /services.yml up -d
